### DISCUSSION TITLE
Querying out specific env vars defined in Kubernetes workloads

### DISCUSSION THREAD

**Discussion by tas50** [mondoohq/cnquery#116] [Q&A] [answered]
Mondoo 6.17 added `env` and `envFrom` data to container resources in Kubernetes. I'd like to use those to look for potentially dangerous env vars that are passing in secrets in plain text.

Give this workload:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: luna-frontend
  namespace: foo
spec:
  containers:
  - name: luna-frontend
    image: lunalectric/frontend:1.0
    env:
    - name: LOGIN
      value: "oh_no"
    - name: PASSWORD
      value: "they_are_really_doing_this!"
```

Using `mondoo shell k8s --path env.yaml` I got to the point of exposing the env vars, but how do I check for multiple names here:

```
mondoo> k8s.pods[0].containers[0].env
k8s.pods[0].containers[0].env: [
  0: {
    name: "LOGIN"
    value: "oh_no"
  }
  1: {
    name: "PASSWORD"
    value: "they_are_really_doing_this!"
  }
]
```
