### DISCUSSION TITLE
Connection string parse

### DISCUSSION THREAD

**Discussion by CedBau** [mondoohq/cnquery#1171] [Q&A]
Hello everyone

As far as I'm concerned NTLM is used for the WinRM connection. I feel like the username isn't parsed correctly if the string contains a slash, e. g. this.domain\username@host. Is there a way around it?

**Comment by chris-rock** [comment]
HI @CedBau

It would be great if you could share the powershell command that you use so that we can see how you connect to the machine. To make sure we do not have a cli parsing issue, you can also use an inventory file:

```yaml
apiVersion: v1
kind: Inventory
spec:
  assets:
    - id: windows-with-password
      connections:
        - host: 192.168.178.20
          backend: winrm
          credentials:
            - user: chris
              password: password
```

and then use

```bash
cnspec scan --inventory-file winrm_inventory.yml 
```
