### DISCUSSION TITLE
MQL Examples for authorizedkeys and authorizedkeys.entry

### DISCUSSION THREAD

**Discussion by kmf** [mondoohq/cnquery#1179] [Q&A] [answered]
Is there MQL examples of using [Authorized Keys](https://mondoo.com/docs/mql/resources/core-pack/authorizedkeys/) and [Authorized Keys Entries](https://mondoo.com/docs/mql/resources/core-pack/authorizedkeys.entry/)?

**Comment by imilchev** [comment]
I suppose you are encountering an error when you try to access this resource. You need to initialize it when invoking it. You can do that as follows:
```
cnspec> authorizedkeys(path: '/root/.ssh/authorized_keys')
authorizedkeys.list: [
  0: authorizedkeys.entry key="***"
  1: authorizedkeys.entry key="***"
]
```
Essentially, you need to provide the path to a file that contains your authorized keys.

**Comment by kmf** [comment]
trying to match output to a list of known keys, how would that look?

**Reply by imilchev** [reply, marked as answer]
Here is an example policy that can do this:

```yaml
policies:
  - uid: sshd-server-policy
    name: SSH Server Policy
    groups:
      - filters: platform.family.contains('linux') # will apply only to assets that run linux
        checks:
          - uid: ssh-authorized-keys
queries:
  - uid: ssh-authorized-keys
    title: Verify SSH authorized keys
    props:
      - uid: allowedKeys # a property that defines the allowed keys. It can be referenced in the query later
        title: Define allowed SSH keys
        mql: |
          return [ 
             "key1", 
             "key2"
          ]
    # The query loads the authorized keys file at /root/.ssh/authorized_keys and then creates a flat list of the keys
    # in that file. Then we verify that this list contains only entries that are present in allowedKeys
    mql: |
      authorizedkeys(path: '/root/.ssh/authorized_keys').map(_.key).containsOnly(props.allowedKeys)
```

This is one way of doing that check. You can play with the MQL a bit if you want to do it differently but this will check what you asked for. 

Let me know if there is something that's not clear!
