### DISCUSSION TITLE
query giving a failure where some field(s) might not exist

### DISCUSSION THREAD

**Discussion by joelddiaz** [mondoohq/cnquery#566] [Q&A] [answered]
I have a query that isn't behaving in a way I would expect.

Given a Pod that looks like:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: joel-test
  namespace: default
spec:
  containers:
    - command:
        - sleep
        - "3600000"
      image: quay.io/fedora/fedora:latest
      name: fedora
      securityContext:
        capabilities:
          drop: ["ALL"]
    - command:
        - sleep
        - "3600000"
      image: quay.io/fedora/fedora:latest
      name: fedora2
```

I would expect that the following query would pass since neither container in the Pod specification have anything specified under .securityContext.capabilities.add:

```yaml
k8s.pod {
      podSpec['containers'] {
          _['securityContext']['capabilities'] {
            _['add'] == null || _['add'].none(_.upcase == "ALL")
          }
      }
    }
```

This passes the first container (named 'fedora'), but fails the second one (named 'fedora2').

I ended up writing an alternative query that does pass:
```yaml
k8s.pod {
      podSpec['containers'] {
        if( _['securityContext']['capabilities'] != null ) {
          _['securityContext']['capabilities'] {
            _['add'] == null || _['add'].none(_.upcase == "ALL")
          }
        } else {
            true
        }
      }
    }
```

This felt a bit verbose (especially that `else true` piece bolted on to the end), and I was wondering if there was a better way to write this kind of query.
