### DISCUSSION TITLE
Does cnspec have the ability to scan multiple AWS accounts?

### DISCUSSION THREAD

**Discussion by chris-rock** [mondoohq/cnquery#736] [Q&A] [answered]
Question from John Anderson in Slack:

We are evaluating this as alternative to what we do with cloud custodian.  Custodian has a tool c7n-org that allows us to run the policies against multiple AWS accounts.  But I don't see a way to say "Run this against all of these accounts", I only see a way to run it against one.

**Comment by chris-rock** [comment]
We have different ways to scan multiple AWS accounts:

1. `cnspec scan aws` which uses your default AWS configuration to connect to the AWS account 
2. We support inventories to scan multiple AWS accounts
3. Mondoo SaaS Platform ships with a full [AWS Org and Account Integration](https://mondoo.com/docs/cloud/aws/overview/)

<img width="929" alt="Screenshot 2023-01-06 at 17 12 14" src="https://user-images.githubusercontent.com/1178413/211051848-75e4667d-2818-4e5b-a8ce-4c631365cb2e.png">

If you want to configure an inventory that scans multiple AWS accounts, use the following setup with an `aws-inventory.yml`:

```
apiVersion: v1
kind: Inventory
metadata:
  name: mondoo-inventory
  labels:
    environment: production
spec:
  assets:
    - id: account-1
      connections:
        - backend: aws
          options:
            profile: example-dev
          discover:
            targets:
              - "accounts"
      annotations:
        owner: user@example.com
    - id: account-2
      connections:
        - backend: aws
          options:
            profile: example-demo
          discover:
            targets:
              - "accounts"
      annotations:
        owner: user@example.com
```

Then you scan the system via:

```
# run aws inventory
cnquery scan --inventory-file aws-inventory.yml

# run aws security scan
cnspec scan --inventory-file aws-inventory.yml 
```

**Comment by chris-rock** [comment, marked as answer]
I updated the example above. It includes references to the aws config of the profiles to use its credentials. The example uses the `accounts` discovery target which focuses purely on the AWS account. You can extend the list with the following entries:

```yaml
apiVersion: v1
kind: Inventory
metadata:
  name: mondoo-inventory
  labels:
    environment: production
spec:
  assets:
    - id: account-1
      connections:
        - backend: aws
          options:
            profile: example-dev
          discover:
            targets:
              - "accounts" # aws account
              - "instances" # ec2 instances
              - "ssm-instances" # ec2 instances with ssm
              - "ecr" # elastic container registry
              - "ecs" # elastic container services
```
