### ISSUE TITLE
Specifying no query filters results in query pack matching no assets

### ISSUE THREAD

**Issue by imilchev** [mondoohq/cnquery#1354]
**Describe the bug**
Writing a query pack that specifies no explicit filters means it will not match any asset.

**To Reproduce**
Steps to reproduce the behaviour:

1. Use the following query pack as an example:
```yaml
packs:
- uid: internal-mondoo-asset-overview
  name: Asset Overview
  queries:
    - uid: internal-mondoo-asset-overview-clientversion
      mql: mondoo.version
      title: Client Version
    - uid: internal-mondoo-asset-overview-platformname
      mql: platform.name
      title: Detected Platform
```
2. Run `cnquery scan local --querypack-bundle pack.yaml`
3. Observe the output
```
Summary (1 assets)
==================

Target:     Ivan-Milchev.local
asset doesn't support any querypacks
```

**Expected behavior**
I would expect that if no filters are specified, then the query pack is applicable to all assets

**Additional context**
If I adjust the pack and add a filter to one of the queries as shown below:
```yaml
packs:
- uid: internal-mondoo-asset-overview
  name: Asset Overview
  queries:
    - uid: internal-mondoo-asset-overview-clientversion
      filters: true == true # <-- this is the important bit
      mql: mondoo.version
      title: Client Version
    - uid: internal-mondoo-asset-overview-platformname
      mql: platform.name
      title: Detected Platform
```
In this case, both queries are executed against my asset:
```
Data (1 assets)
===============

Asset: Ivan-Milchev.local
-------------------------

Client Version:
mondoo.version: "v8.18.0"

Detected Platform:
platform.name: "macos"

Summary (1 assets)
==================

Target:     Ivan-Milchev.local
Datapoints: 2
```

It seems like the query execution code correctly treats no filters as always applicable. However, the code that decides whether a pack is applicable to an asset, doesn't do this correctly
