### ISSUE TITLE
Extend `k8s.node` with manifest and properties for cpu and memory

### ISSUE THREAD

**Issue by czunker** [mondoohq/cnquery#1466]
**Is your feature request related to a problem? Please describe.**
We currently only provide limited data on `k8s.node` resources.

**Describe the solution you'd like**
We should extend the resource to include the complete manifest, as we already do for other resources, e.g., `k8s.pod`: https://github.com/mondoohq/cnquery/blob/v8/resources/packs/k8s/k8s.lr#L145

In case of `k8s.node` we should also expose `status.allocatable` and `status.capacity` as explicit properties. Both can be of type dict.

This will allow us to query data like CPU and memory:
```
status:
  allocatable:
    attachable-volumes-gce-pd: "127"
    cpu: 3920m
    ephemeral-storage: "18828602911"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 13604896Ki
    pods: "110"
  capacity:
    attachable-volumes-gce-pd: "127"
    cpu: "4"
    ephemeral-storage: 47227284Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 16393248Ki
    pods: "110"
```

**Describe alternatives you've considered**
-

**Additional context**
-
