### ISSUE TITLE
YAML output does not always generate valid yaml

### ISSUE THREAD

**Issue by mbainter** [mondoohq/cnquery#2107]
**Describe the bug**
When running the mondoo inventory query pack with a yaml output format the yaml that gets generated is invalid - with duplicate key names under the asset map

**To Reproduce**

1. run cnquery scan vsphere --querypack-bundle cnquery-packs/extra/mondoo-asset-count.mql.yaml -o yaml 
2. examine the yaml output under the assets field

It doesn't have to be vsphere, but it needs to be a scan that identifies multiple assets.

**Expected behavior**
The YAML should be valid, which means under assets, it should probably be a list of objects, like this:
```yaml
assets:
    - mrn: //explorer.api.mondoo.com/assets/abc123
      name: 0.0.0.1
    - mrn: //explorer.api.mondoo.com/assets/def456
      name: 0.0.0.2
    - mrn: //explorer.api.mondoo.com/assets/efg789
      name: 0.0.0.3
```

**Screenshots or CLI Output**
The YAML looks like:

```yaml
assets:
    mrn: //explorer.api.mondoo.com/assets/abc123
    name: 0.0.0.1
    mrn: //explorer.api.mondoo.com/assets/def456
    name: 0.0.0.2
    mrn: //explorer.api.mondoo.com/assets/efg789
    name: 0.0.0.3
```

**Desktop (please complete the following information):**

Linux, PopOS 22.04.
CNQuery 8.28.4
