### ISSUE TITLE
provider download behind forward proxy not working

### ISSUE THREAD

**Issue by atomic111** [mondoohq/cnquery#2206]
all my systems are behind a forward proxy (no direct internet access). the cnquery/ cnspec client is not using the proxy configuration in the mondoo.yml to download the providers

mondoo.yml:

```yaml
api_endpoint: https://us.api.mondoo.com
api_proxy: http://10.0.101.53:3128
auto_update: true
```

the registration of the cnquery/cnspec client behind the proxy is working is working

```bash
cnspec login -t <token> --api-proxy http://10.0.101.53:3128
```

```bash
cnspec shell local
! Get "https://releases.mondoo.com/providers/latest.json": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
→ connected to Red Hat Enterprise Linux 9.2 (Plow)
  ___ _ __  ___ _ __   ___  ___
 / __| '_ \/ __| '_ \ / _ \/ __|
| (__| | | \__ \ |_) |  __/ (__
 \___|_| |_|___/ .__/ \___|\___|
   mondoo™     |_|
cnspec>
```
