### ISSUE TITLE
When using groups in a query pack, they must all have a filter

### ISSUE THREAD

**Issue by tas50** [mondoohq/cnquery#2219]
Given this policy:

```yaml
packs:
  - uid: tim-test
    name: Reproduce the bug
    version: 1.0.0
    license: proprietary
    authors:
      - name: Mondoo, Inc
        email: hello@mondoo.com
    tags:
      mondoo.com/platform: azure,cloud,macos,windows,host
      mondoo.com/category: compliance
    docs:
      desc: |
        This query pack will show the bug
    groups:
      - title: Asset inventory
        queries:
          - uid: tim-test-asset-data
      - title: Azure
        filters: asset.platform == 'azure'
        queries:
          - uid: tim-test-query-1
          - uid: tim-test-query-2
          - uid: tim-test-query-3
    queries:
      - uid: tim-test-query-1
        title: Query 1
        docs:
          desc: |
            Description Time
        mql: asset.platform
      - uid: tim-test-query-2
        title: Query 2
        docs:
          desc: |
            Description Time
        mql: asset.platform
      - uid: tim-test-query-3
        title: Query 3
        docs:
          desc: |
            Description Time
        mql: asset.platform
      - uid: tim-test-asset-data
        title: Asset 1
        docs:
          desc: |
            Description Time
        mql: asset.platform
```

I get this error trying to run it:

```
cnquery scan azure --querypack-bundle tim-test.mql.yml
→ loaded configuration from /Users/tsmith/.config/mondoo/mondoo.yml using source default
→ using service account credentials
! Scanning with local bundles will switch into --incognito mode by default. Your results will not be sent upstream.
→ discover related assets for 1 asset(s)

 Azure subscription 1           ──────────────────────────────────────────────────────────────────────────────────────────────────────────    X
 Azure subscription 2 ──────────────────────────────────────────────────────────────────────────────────────────────────────────    X
 Azure subscription 3                ──────────────────────────────────────────────────────────────────────────────────────────────────────────    X
 Azure subscription 4            ──────────────────────────────────────────────────────────────────────────────────────────────────────────    X

 0/4 scanned 4/4 errored                       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100%

Summary (4 assets)
==================

Target:     Azure subscription 1
error: cannot compute filters for a querypack, unless it was compiled first

Target:     Azure subscription 2
error: cannot compute filters for a querypack, unless it was compiled first

Target:     Azure subscription 3
error: cannot compute filters for a querypack, unless it was compiled first

Target:     Azure subscription 4
error: cannot compute filters for a querypack, unless it was compiled first
```
