### ISSUE TITLE
cnquery fails to compile bundle with variants

### ISSUE THREAD

**Issue by tas50** [mondoohq/cnquery#2279]
**Describe the bug**
So this could entirely be me not writing the querypack correct. Apologies if that's the case. I'm just cargo culting and going off the MQL docs.

### Goal

Have a group that contains a single query which varies based on the platform.

### The code

```yaml
packs:
  - uid: tim-query-pack
    name: Tim Query Pack
    version: 1.0.0
    license: proprietary
    authors:
      - name: Mondoo, Inc
        email: hello@mondoo.com
    docs:
      desc: |
        Queries some stuff
    groups:
      - title: Asset inventory
        filters: "true"
        queries:
          - uid: tim-query-pack-asset-data
      - title: Azure
        filters: asset.platform == 'azure'
        queries:
          - uid: tim-query-pack-azure-public-ips
    queries:
      - uid: tim-query-pack-azure-public-ips
        title: Azure public IP addresses configuration
        docs:
          desc: |
            Get public IPs
        mql: azure.subscription.networkService.publicIpAddresses{ name location ipAddress tags }
      - uid: tim-query-pack-asset-data
        title: Inventory data for all assets
        docs:
          desc: |
            Query all the things
        variants:
          - uid: tim-query-pack-asset-inventory-macos
          - uid: tim-query-pack-asset-inventory-windows
          - uid: tim-query-pack-asset-inventory-azure
          - uid: tim-query-pack-asset-data-hosts
      - uid: tim-query-pack-asset-data-macos
        filters: asset.platform == "macos"
        mql: |
          asset {
            name
            platform
            version
            arch
          }
      - uid: tim-query-pack-asset-data-windows
        filters: asset.platform == "windows"
        mql: |
          asset {
            name
            platform
            version
            build
          }
      - uid: tim-query-pack-asset-data-azure
        filters: asset.platform == "azure"
        mql: |
          asset {
            name
            azure.subscription.subscriptionId
            azure.subscription.tenantId
          }
      - uid: tim-query-pack-asset-data-hosts
        filters: asset.platform == "host"
        mql: |
          asset {
            name
          }
          http.get{
            version
          }
          tls.versions
```

### Results

```
$ cnquery scan azure --querypack-bundle tim.mql.yaml
→ loaded configuration from /Users/tsmith/.config/mondoo/mondoo.yml using source default
→ using service account credentials
! Scanning with local bundles will switch into --incognito mode by default. Your results will not be sent upstream.
FTL failed to resolve query packs error="failed to compile bundle: failed to register filters for query //local.cnquery.io/run/local-execution/queries/mondoo-compliance-inventory-asset-data\n"
```

**Comment by arlimus** [comment]
Ok super comprehensive answer and thank you for submitting everything

1. There was a bug that caused variants in local cnquery bundle compiles to be processed a bit late. Solved in https://github.com/mondoohq/cnquery/pull/2360
2. You need to specify shared queries as being shared in the querypack, otherwise you are telling the pack to run every variant that applies always, alongside the variant-holder. What you want is just one, i.e. the variant-holder. See the examples folder [`complex.mql.yaml`](https://github.com/mondoohq/cnquery/blob/main/examples/complex.mql.yaml) 
3. Last one is to actually using the same UIDs :grin: 

```yaml
packs:
  - uid: tim-query-pack
    name: Tim Query Pack
    version: 1.0.0
    license: proprietary
    authors:
      - name: Mondoo, Inc
        email: hello@mondoo.com
    docs:
      desc: |
        Queries some stuff
    groups:
      - title: Asset inventory
        filters: "true"
        queries:
          - uid: tim-query-pack-asset-data
      - title: Azure
        filters: asset.platform == 'azure'
        queries:
          - uid: tim-query-pack-azure-public-ips
    queries:
      - uid: tim-query-pack-azure-public-ips
        title: Azure public IP addresses configuration
        docs:
          desc: |
            Get public IPs
        mql: azure.subscription.networkService.publicIpAddresses{ name location ipAddress tags }
      - uid: tim-query-pack-asset-data
        title: Inventory data for all assets
        docs:
          desc: |
            Query all the things
        variants:
          - uid: tim-query-pack-asset-data-macos
          - uid: tim-query-pack-asset-data-windows
          - uid: tim-query-pack-asset-data-azure
          - uid: tim-query-pack-asset-data-hosts

queries:
- uid: tim-query-pack-asset-data-macos
  filters: asset.platform == "macos"
  mql: |
    asset {
      name
      platform
      version
      arch
    }
- uid: tim-query-pack-asset-data-windows
  filters: asset.platform == "windows"
  mql: |
    asset {
      name
      platform
      version
      build
    }
- uid: tim-query-pack-asset-data-azure
  filters: asset.platform == "azure"
  mql: |
    asset {
      name
      azure.subscription.subscriptionId
      azure.subscription.tenantId
    }
- uid: tim-query-pack-asset-data-hosts
  filters: asset.platform == "host"
  mql: |
    asset {
      name
    }
    http.get{
      version
    }
    tls.versions
```
