### ISSUE TITLE
`scan k8s <manifest-file>` does not work for some files

### ISSUE THREAD

**Issue by czunker** [mondoohq/cnquery#2302]
**Describe the bug**
```
cnquery scan k8s .github/test_files/k8s-manifest.yaml --verbose                                                                                                                                                                                                                                                            
DBG using provider k8s with connector k8s
DBG Started a new runtime (1 total)
DBG running provider plugin path=/home/christian/.config/mondoo/providers/k8s/k8s
DBG Started a new runtime (2 total)
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
→ using service account credentials
→ discover related assets for 1 asset(s)
DBG Started a new runtime (3 total)
DBG resolved 2 assets
DBG Started a new runtime (4 total)
DBG Started a new runtime (5 total)
→ synchronize assets
DBG initialize client authentication issuer=mondoo/ams kid=//agents.api.mondoo.app/spaces/dazzling-golick-767384/serviceaccounts/2AyMRoi8pfJa6gOqq16QWstmKPK
DBG non-ok http request body="could not sync assets" status=500
FTL failed to run scan error="rpc error: code = Internal desc = could not sync assets"
```
The same happens for cnspec.

This is the used file: https://github.com/mondoohq/actions/blob/main/.github/test_files/k8s-manifest.yaml

Bug was observed here: https://github.com/mondoohq/actions/actions/runs/6571602900/job/17851138836?pr=73

But also happens when running locally.

**To Reproduce**

1. Run above command with the **mentioned** file
2. Note the error

**Expected behavior**
The manifest file should get scanned.

**Desktop (please complete the following information):**

- cnquery/cnspec v9.2.2
- k8s 9.0.13 with connectors: k8s

**Additional context**
I gave it a try with another file and that worked. Will add it to a comment.

An `incognito` scan of the actions test file works:
```
cnspec scan k8s .github/test_files/k8s-manifest.yaml --incognito                                                                                                                                                                                                                                                            → loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
→ discover related assets for 1 asset(s)

...

Asset: mondoo-operator/mondoo-operator-controller-manager
---------------------------------------------------------

Checks:
✓ Pass:  A 100  Container should have a memory limit
✓ Pass:  A 100  Container should request CPU
✓ Pass:  A 100  Container should configure a livenessProbe
✓ Pass:  A 100  Pods should not run Kubernetes dashboard
✓ Pass:  A 100  Container should not mount the Docker socket
✓ Pass:  A 100  Deployments should not run in the default namespace
✓ Pass:  A 100  Deployments should not run Tiller (Helm v2)
✓ Pass:  A 100  Container should not mount the containerd socket
✓ Pass:  A 100  Container should configure a readinessProbe
✓ Pass:  A 100  Container should not run as root
✓ Pass:  A 100  Container should not allow privilege escalation
✓ Pass:  A 100  Deployments should not bind to a host port
✕ Fail:  C  40  Container image pull should be consistent
✓ Pass:  A 100  Container should not mount the CRI-O socket
✓ Pass:  A 100  Pod should not run with the default service account
✓ Pass:  A 100  Pod should not define hostAliases
✓ Pass:  A 100  Deployments should not run with SYS_ADMIN capability
✓ Pass:  A 100  Deployments should mount any host path volumes as read-only
✓ Pass:  A 100  Container should use an immutable root filesystem
✓ Pass:  A 100  Pod should not run with hostPID
✕ Fail:  D  20  Deployments should not run with NET_RAW capability
✓ Pass:  A 100  Container should request memory
✓ Pass:  A 100  Container should not run as a privileged container
✓ Pass:  A 100  Pod should not run with hostNetwork
✓ Pass:  A 100  Container should have a CPU limit
✓ Pass:  A 100  Pod should not run with hostIPC

Vulnerabilities:
error: Could not find the vulnerability report.

Scanned 2 assets

Kubernetes Deployment
    B mondoo-operator/mondoo-operator-controller-manager

Kubernetes Manifest
    X 

Summary
=======

Score Distribution		Asset Distribution
------------------		------------------
A   0 assets      		Kubernetes Manifest     1
B   1 assets      		Kubernetes Deployment   1
C   0 assets
D   0 assets
F   0 assets
X   1 assets
```

**Comment by czunker** [comment]
The scan works for this file:
```
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    admission-result: pass
  name: passing-pod-yaml
  namespace: default
spec:
  automountServiceAccountToken: false
  containers:
  - image: ubuntu:20.04
    imagePullPolicy: Always
    command: ["/bin/sh", "-c"]
    args: ["sleep 6000"]
    livenessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - exit 0
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: ubuntu
    readinessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - exit 0
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 100Mi
    securityContext:
      allowPrivilegeEscalation: false
      privileged: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  securityContext: {}
  serviceAccountName: mondoo-operator-controller-manager
  terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    admission-result: pass
  name: passing-pod-yaml-2
  namespace: default
spec:
  automountServiceAccountToken: false
  containers:
  - image: ubuntu:20.04
    imagePullPolicy: Always
    command: ["/bin/sh", "-c"]
    args: ["sleep 6000"]
    livenessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - exit 0
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: ubuntu
    readinessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - exit 0
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 100Mi
    securityContext:
      allowPrivilegeEscalation: false
      privileged: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  securityContext: {}
  serviceAccountName: mondoo-operator-controller-manager
  terminationGracePeriodSeconds: 30
```
