### ISSUE TITLE
cnquery/ cnspec not working with vault configuration

### ISSUE THREAD

**Issue by atomic111** [mondoohq/cnquery#2313]
i have an existing vault with the credentials for my vcenter that is configured in my inventory.yml

```yaml
apiVersion: v1
kind: Inventory
metadata:
  name: cnspec-inventory
  labels:
    environment: production
spec:
  assets:
    - name:
      connections:
        - backend: vsphere
          host: 192.168.5.24
          credentials:
            - secret_id: vcenter
          discover:
            targets:
              - host-machines
  vault:
    name: mondoo-client-vault
    options:
      password: changemeifyoucan
      path: /etc/opt/mondoo/vault.enc
    type: encrypted-file
```

if I execute a scan with my cnspec version 9.2.3, I get the following error

```bash
cnspec scan --inventory-file ./inventory-enc-file-test.yml
→ no provider specified, defaulting to local. Use --help to see all providers.
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
→ load inventory inventory-file=./inventory-enc-file-test.yml
! no connection `type` provided in inventory, falling back to deprecated `backend` field
→ using service account credentials
→ discover related assets for 1 asset(s)
FTL failed to run scan error="failed to resolve inventory for connection"
```

Maybe this issue is connect with https://github.com/mondoohq/cnquery/issues/2271
