### ISSUE TITLE
cnquery does not parse `namespaces-exclude` in inventory file

### ISSUE THREAD

**Issue by czunker** [mondoohq/cnquery#2805]
**Describe the bug**
I've a minikube running, with 7 images:
```
k get pods -A -o yaml | yq '.items[].spec.containers[].image 
registry.k8s.io/coredns/coredns:v1.10.1
registry.k8s.io/etcd:3.5.9-0
registry.k8s.io/kube-apiserver:v1.28.3
registry.k8s.io/kube-controller-manager:v1.28.3
registry.k8s.io/kube-proxy:v1.28.3
registry.k8s.io/kube-scheduler:v1.28.3
gcr.io/k8s-minikube/storage-provisioner:v5
```

When I scan these images with CLI parameters, only 3 are left:
```
cnquery scan k8s --discover container-images --namespaces-exclude kube-system,mondoo-operator --config ~/workspace/mondoo/sa-edge-default.json --verbose
...
DBG resolved 3 assets
```

When I add these parameters to an inventory file, I get all 7 images:
```
cnquery scan k8s --inventory-file ./k8s-inventory.yaml --config ~/workspace/mondoo/sa-edge-default.json --verbose 
...
DBG resolved 7 assets
```

**To Reproduce**

1. Set up minikube
2. Scan with inventory file
3. Note the additional images

**Expected behavior**
Both should result in te same number of images.

**Desktop (please complete the following information):**

- cnquery 9.10.0

**Additional context**
The inventory file:
```
metadata:
  name: mondoo-k8s-inventory
spec:
  assets:
    - id: ""
      connections:
      - id: 0
        type: k8s
        options:
          namespaces-exclude: mondoo-operator,kube-system
        discover:
          targets:
          - container-images
```
