### ISSUE TITLE
AWS Provider `panic: runtime error: invalid memory address or nil pointer dereference`

### ISSUE THREAD

**Issue by mm-weber** [mondoohq/cnquery#3245]
**Describe the bug**

Using the Mondoo Development account, when running `cnspec scan aws -f ~/projects/cnspec-enterprise-policies/policies/aws-foundations-benchmark.mql.yaml -o full --discover s3-buckets`, this will run into the following error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x573e6e0]

goroutine 1605 [running]:
go.mondoo.com/cnquery/v10/providers/aws/resources.(*mqlAwsS3Bucket).MqlID(0xd00000000000022?)
	/home/runner/_work/cnquery/cnquery/providers/aws/resources/aws.lr.go:16411
go.mondoo.com/cnquery/v10/llx.resource2result({0x65be7a0, 0x0}, {0xc0000125f0, 0xe})
	/home/runner/_work/cnquery/cnquery/llx/data_conversions.go:321 +0x52
go.mondoo.com/cnquery/v10/llx.raw2primitive({0x65be7a0, 0x0}, {0xc0000125f0, 0xe})
	/home/runner/_work/cnquery/cnquery/llx/data_conversions.go:352 +0x142
go.mondoo.com/cnquery/v10/llx.(*RawData).Result(0xc00135b650)
	/home/runner/_work/cnquery/cnquery/llx/data_conversions.go:377 +0x77
go.mondoo.com/cnquery/v10/providers-sdk/v1/plugin.(*TValue[...]).ToDataRes(0x71bbac0?, {0xc0000125f0?, 0x6634bb3?})
	/home/runner/_work/cnquery/cnquery/providers-sdk/v1/plugin/runtime.go:185 +0x1e7
go.mondoo.com/cnquery/v10/providers/aws/resources.glob..func547({0x71de828?, 0xc001450a00?})
	/home/runner/_work/cnquery/cnquery/providers/aws/resources/aws.lr.go:2348 +0x6b
go.mondoo.com/cnquery/v10/providers/aws/resources.GetData({0x71de828, 0xc001450a00}, {0xc0000125e8, 0x8}, 0x22?)
	/home/runner/_work/cnquery/cnquery/providers/aws/resources/aws.lr.go:3633 +0x16b
go.mondoo.com/cnquery/v10/providers/aws/provider.(*Service).GetData(0x63691a0?, 0xc00075e0e0)
	/home/runner/_work/cnquery/cnquery/providers/aws/provider/provider.go:317 +0x3ea
go.mondoo.com/cnquery/v10/providers-sdk/v1/plugin.(*GRPCServer).GetData(0x641cae0?, {0xc00075e0e0?, 0x4d0446?}, 0x0?)
	/home/runner/_work/cnquery/cnquery/providers-sdk/v1/plugin/grpc.go:121 +0x1e
go.mondoo.com/cnquery/v10/providers-sdk/v1/plugin._ProviderPlugin_GetData_Handler({0x63691a0?, 0xc0005c4f80}, {0x7275298, 0xc001d00690}, 0xc001f86100, 0x0)
	/home/runner/_work/cnquery/cnquery/providers-sdk/v1/plugin/plugin_grpc.pb.go:266 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002be200, {0x7275298, 0xc001d005a0}, {0x727aee0, 0xc000c9e340}, 0xc001bb4360, 0xc000c09b00, 0x95ebd38, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.61.0/server.go:1385 +0xe03

                                             ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% score: X
 aws-cloudtrail-logs-12345678-0bf3a306   

 1/1 scanned                               ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100%

x plugin process exited error="exit status 2" id=785575 plugin=/home/manuel/.config/mondoo/providers/aws/aws
x the 'aws' provider crashed: rpc error: code = Unavailable desc = error reading from server: EOF
Asset: //policy.api.mondoo.com/assets/2c6Aa67PVczZsbADTB1kLs14qIu
-----------------------------------------------------------------

Data queries:
null

Checks:
! Error:        Ensure S3 Bucket Policy is set to deny HTTP requests
  Message:      1 error occurred:
	* rpc error: code = Unavailable desc = connection error: desc = "transport: error while dialing: dial unix /tmp/plugin920801413: connect: connection refused"

! Error:        Ensure IAM policies that allow full "*:*" administrative privileges are not attached
  Message:      1 error occurred:

```

**To Reproduce**

Run `cnspec scan aws -f ~/projects/cnspec-enterprise-policies/policies/aws-foundations-benchmark.mql.yaml -o full --discover s3-buckets` from current `main`/`b324e874`from `cnspec-enterprise-policies`

**Expected behavior**

**Screenshots or CLI Output**
If applicable, add screenshots or the CLI output to help explain your problem.

**Desktop (please complete the following information):**

```
cnspec v10.2.0 (a8defa1, unknown)
cnquery v10.2.0 (4d9e59ef, unknown)
```

**Additional context**

**Comment by mm-weber** [comment]
Was able to pinpoint it to (at least) one `variants:` check:

```
# Copyright (c) Mondoo, Inc.
# SPDX-License-Identifier: BUSL-1.1

# Read more about the policy structure at https://mondoo.com/docs
policies:
  - uid: aws-sec-groupolicy
    name: aws sec group Policy
    version: 1.0.0
    tags:
      another-key: another-value
      key: value
    authors:
      - name: Jane Doe
        email: jane@example.com
    groups:
      - title: Bucket-Test
        filters: |
          asset.platform == "aws" || asset.platform == "aws-s3-bucket" || asset.platform == "terraform-hcl" ||  asset.platform == "aws-cloudtrail-trail"
        checks:
          - uid: aws-cloudtrail-s3-bucket-used-store-cloudtrail-logs-publicly-accessible
queries:
  - uid: aws-cloudtrail-s3-bucket-used-store-cloudtrail-logs-publicly-accessible
    title: Ensure the S3 bucket used to store CloudTrail logs is not publicly accessible
    impact: 60
    variants:
      - uid: aws-cloudtrail-s3-bucket-used-store-cloudtrail-logs-publicly-accessible-api
      - uid: aws-cloudtrail-s3-bucket-used-store-cloudtrail-logs-publicly-accessible-single
  - uid: aws-cloudtrail-s3-bucket-used-store-cloudtrail-logs-publicly-accessible-api
    filters: asset.platform == "aws"
    mql: |
      aws.cloudtrail.trails.all(
        s3bucket.public == false &&
          aws.cloudtrail.trails.where(s3bucket.policy != empty).all(
            s3bucket.policy.statements.where(Effect == "Allow").none(Principal.Service == "*")
          )
      )
  - uid: aws-cloudtrail-s3-bucket-used-store-cloudtrail-logs-publicly-accessible-single
    filters: |
      asset.platform == "aws-cloudtrail-trail"
      aws.cloudtrail.trail.s3bucket.policy != empty
    mql: |
      aws.cloudtrail.trail.s3bucket.public == false
      aws.cloudtrail.trail.s3bucket.policy.statements.where(Effect == "Allow").none(Principal.Service == "*")

```
