### ISSUE TITLE
Feature request: GKE  `gcp.project.gke.binauthz.policy` field.

### ISSUE THREAD

**Issue by mm-weber** [mondoohq/cnquery#4044]
Is it possible to add the following resource:

## Command
```
gcloud container binauthz policy export 
```
## Output
```
defaultAdmissionRule:
  enforcementMode: ENFORCED_BLOCK_AND_AUDIT_LOG
  evaluationMode: ALWAYS_DENY
etag: '"NEocAnCaAQ1d"'
globalPolicyEvaluationMode: ENABLE
name: projects/xxx-development-3/policy
updateTime: '2024-05-21T12:13:44.314367Z'
```

## Suggested call
`gcp.project.gke.binauthz.policy.` ?
