### ISSUE TITLE
Issue with some Test Errors in cnquery Scans (Exchange server 2019)

### ISSUE THREAD

**Issue by HRouhani** [mondoohq/cnquery#4256]
**Summary:**

The scan runs successfully overall; however, some specific tests encounter errors consistently. The error message for these tests is:

```
! Error:      Ensure 'External send connector authentication: DNS routing' is set to 'True'                                                                                                                        
  Message:    1 error occurred:                                                                                                                                                                                    
        * could not convert []interface {} to block 
```

Notably, these tests execute without any issues when run directly from the shell.

Text example:   test.mql.yaml

```
# Read more about the policy structure at https://mondoo.com/docs
policies:
  - uid: cis-microsoft-exchange-server-2019-es-level
    name: SSH Server Policy
    version: 1.0.0
    tags:
      another-key: another-value
      key: value
    authors:
      - name: Jane Doe
        email: jane@example.com
    docs:
      desc: |-
    groups:
      - uid: cis-microsoft-exchange-server-2019-es-level-1--1
        title: Edge Transport Server
        filters: |
          asset.platform == "windows"
          asset.version == 17763
        checks:
          - uid: cis-microsoft-exchange-server-2019--external-send-connector-authentication-dns-routing-set-true
queries:
  - uid: cis-microsoft-exchange-server-2019--external-send-connector-authentication-dns-routing-set-true
    title: 'Ensure ''External send connector authentication: DNS routing'' is set to ''True'''
    impact: 80
    tags:
      cisecurity.org/recommendation: "1.12"
    mql: |
     parse.json(content: powershell("
        Add-PSSnapin Microsoft.Exchange.Management.PowerShell.SnapIn;
        $connector = Get-SendConnector | Select-Object DNSRoutingEnabled;
        $connector | ConvertTo-Json
      ").stdout).params {DNSRoutingEnabled == true}
```

The error appears when customer has several Connectors in this case. 

![Screenshot from 2024-06-18 10-28-08](https://github.com/mondoohq/cnquery/assets/56231339/38b560c8-3da2-4159-ba39-906629869e0c)

![Screenshot from 2024-06-18 10-29-10](https://github.com/mondoohq/cnquery/assets/56231339/b4be2be3-1843-4a7f-b34c-a994e0f05a75)

**Expected Behavior:**

The test should pass without any errors during the cnquery scan, just as it does when the PowerShell command is executed directly from the shell.

**Actual Behavior:**
The test fails with the error: could not convert []interface {} to block.

**Possible Cause:**
The error suggests that there might be an issue with how cnquery processes the output of the PowerShell command or converts the JSON result.

**Suggested Fix:**
Investigate the output format of the PowerShell command and ensure it is compatible with the expected input format for cnquery.
Review the JSON parsing logic within cnquery to handle the output correctly.

Important:

Using .all() is not an option here, as in the case of single connector, it is not able to make a proper comparison as can be seen here:

```
parse.json(content: powershell("
        Add-PSSnapin Microsoft.Exchange.Management.PowerShell.SnapIn;
        $connector = Get-SendConnector | Select-Object DNSRoutingEnabled;
        $connector | ConvertTo-Json
      ").stdout).params.all(DNSRoutingEnabled == true)

	[failed] [].all()
  actual:   {
    DNSRoutingEnabled: true
  }
```
