### ISSUE TITLE
Can't scan the output of the `ansible-inventory` command (pipe method)

### ISSUE THREAD

**Issue by misterpantz** [mondoohq/cnquery#4846]
**Describe the bug**
(Originally reported as a docs issue by @atomic111)

`ansible-inventory -i hosts.ini --list | cnspec scan --inventory-format-ansible` scans notebook but not the target that is defined in the inventory

shell is zsh

```
ansible-inventory -i inventory-test.yml --list | cnspec scan --inventory-format-ansible
→ no provider specified, defaulting to local. Use --help to see all providers.
→ loaded configuration from /Users/user/.config/mondoo/mondoo.yml using source default
→ using service account credentials
→ discover related assets for 1 asset(s)

 notebook 
────────────────────────────────   0%
→ synchronize assets
```

inventory file:

```
all:
  vars:
    ansible_connection: ssh
    ansible_port: 22
  hosts:
    debian12:
      ansible_host: 1.176.111.111
      ansible_user: admin
      ansible_ssh_private_key_file: ~/.ssh/key-rsa
```

**To Reproduce**

Run `ansible-inventory -i hosts.ini --list | cnspec scan --inventory-format-ansible` on an inventory file like the one above.

**Expected behavior**
cnspec scans inventory file

**Screenshots or CLI Output**

```
ansible-inventory -i inventory-test.yml --list | cnspec scan --inventory-format-ansible
→ no provider specified, defaulting to local. Use --help to see all providers.
→ loaded configuration from /Users/user/.config/mondoo/mondoo.yml using source default
→ using service account credentials
→ discover related assets for 1 asset(s)

 notebook 
────────────────────────────────   0%
→ synchronize assets
```

**Desktop (please complete the following information):**

using zsh

**Additional context**
Scanning Ansible inventory hosts.json does work fine. It's only the pipe method that isn't working.
