### ISSUE TITLE
improve slow microsoft query

### ISSUE THREAD

**Issue by vjeffrey** [mondoohq/cnquery#5110]
```
 microsoft.users.any(userPrincipalName == /emergency/)
 emrgID = microsoft.users.where(userPrincipalName == /emergency/).map(id)
 microsoft.rolemanagement.roleDefinitions.where(displayName == "Global Administrator").all(assignments.any(principalId == emrgID))
```

this query has been found to be very slow in large environments. we need to investigate how to improve it.

**Comment by vjeffrey** [comment]
two possible ways to speed this up:

- allow fetching of users by userPrincipalName so we don't have to use a where clause there
- allow fetching of role definitions by display name so we don't need to use a where clause there

**Comment by vjeffrey** [comment]
being able to query
```
 emrgID = microsoft.users(userPrincipalName == /emergency/).map(id)
 microsoft.rolemanagement.roleDefinitions(displayName == "Global Administrator").all(assignments.any(principalId == emrgID))
```
would make this easier

**Comment by afiune** [comment]
Ideally, I will solve this problem by introducing a filter at the list resource level but since this is the first time we will do that, I will write an RFC for something like `microsoft.users(filter: "userPrincipalName:foo")`

If this works, the policy will have to be rewritten to something like:
```yaml
- uid: mondoo-microsoft-entraid-emergency-account
    title: Ensure at Least One Emergency Access Account is Defined
    impact: 90
    filters: |
      asset.platform == "microsoft365"
    props:
      - uid: emergencyAccountFilter
        title: This filters the emergency account using the userPrincipalName.
        mql: |
          return "userPrincipalName:emergency"
    mql: |
      microsoft.users(filter: props.emergencyAccountFilter)
      emrgID = microsoft.users(filter: props.emergencyAccountFilter).map(id)
      microsoft.rolemanagement.roleDefinitions(filter: "displayName:Global Administrator").all(assignments.any(principalId == emrgID))
```
