### ISSUE TITLE
GCP: Add support for checking Public Access Prevention to gcp.storage.bucket resource

### ISSUE THREAD

**Issue by scottford-io** [mondoohq/cnquery#873]
**Is your feature request related to a problem? Please describe.**
cnquery and cnspec should provide the ability to check for [Public Access Prevention](https://cloud.google.com/storage/docs/public-access-prevention) on Cloud Storage buckets. Public Access Prevention can be configured via an Org policy, or on an individual bucket level. I believe GCP org admins will need the ability to audit both that the org is set, as well as prove that every bucket is either  set to `inherited` or `enforced`. 

This feature request is limited to per-bucket check using the `gcp.storage.bucket` resource.

Using the `gcloud storage buckets list` command, the `iamConfiguration` does show `publicAccessPrevention` as being either `inherited` or `enforced`

```
iamConfiguration:
  bucketPolicyOnly:
    enabled: false
  publicAccessPrevention: inherited
  uniformBucketLevelAccess:
    enabled: false
```

```
iamConfiguration:
  bucketPolicyOnly:
    enabled: true
    lockedTime: '2023-04-30T06:11:51.725000+00:00'
  publicAccessPrevention: enforced
  uniformBucketLevelAccess:
    enabled: true
    lockedTime: '2023-04-30T06:11:51.725000+00:00'
```

**Describe the solution you'd like**
A query should be possible to check the configuration of publicAccessPrevention

The following is an example that uses cnquery to check the `publicAccessPrevention` configuration for all buckets:

```
gcp.storage.buckets { iamConfiguration['publicAccessPrevention']  }
```

Here are two assertions with cnspec

```
gcp.storage.buckets.all( iamConfiguration['publicAccessPrevention']  == "enforced" )
gcp.storage.buckets.all( iamConfiguration['publicAccessPrevention']  == "inherited" )
```

**Additional context**
